"Who was the first person to set foot on the Moon"
    "What is the capital of Canada"
    "Who wrote the famous play Romeo and Juliet"
    "Which planet is known as the Red Planet"
    "What is the chemical symbol for gold"
    "What does HTML stand for"
    "What is the output of print(2 ** 3) in Python"
    "Which data structure follows the Last In First Out LIFO principle"
    "In JavaScript which keyword is used to declare a constant variable"
    "What does the acronym SQL stand for"
    "Who painted the Mona Lisa"
    "What is the largest ocean on Earth"
    "Which country is known as the Land of the Rising Sun"
    "Who discovered gravity"
    "How many continents are there on Earth"
    "What is the longest river in the world"
    "What is the national currency of Japan"
    "Who was the first President of the United States"
    "What is the smallest planet in the Solar System"
    "Which country gifted the Statue of Liberty to the United States"
    "What is the tallest mountain in the world"
    "Which scientist developed the theory of relativity"
    "What is the main ingredient in traditional sushi"
    "Which language has the most native speakers in the world"
    "How many bones are there in the human body"
    "What is the capital city of Australia"
    "Which animal is known as the King of the Jungle"
    "What is the square root of 64"
    "Which country is famous for the Eiffel Tower"
    "What does the acronym NASA stand for"
